version: '3'

services:
  submission_telebot:
    image: "hormones/submission_telebot"
    container_name: "submission_telebot"
    build:
      context: .
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config.yml:/app/config.yml
      - ./appdata:/app/appdata
